### ISSUE TITLE
【建议】将badjs体系下相关服务配置单独抽离出来

### ISSUE THREAD

**Issue by chyingp** [BetterJS/doc#10]
先举一个配置关联的小例子：
1. 从 `badjs-web/project.debug.json`中的配置来看， `badjs-storage`启动的服务监听了 **9000** 端口，来提供错误日志查询服务。

```
    "storage" : {
        "errorMsgTopUrl" : "http://127.0.0.1:9000/errorMsgTop",
        "errorMsgTopCacheUrl" : "http://127.0.0.1:9000/errorMsgTopCache",
        "queryUrl" : "http://127.0.0.1:9000/query"
    },
```
1. 扒了下 `badjs-storage/service/query.js`，的确是这样。

```
.listen(9000);
```
1. 也就是说，两个服务之间的端口其实是密切相关的

**建议：**
1. 将端口9000的配置抽取出来 -- 这边使用过程中，9000端口跟服务器上的其他服务冲突了，得去修改badjs-storage的源码（只是改端口）
2. 将badjs体系下相关服务的配置统一抽离到一块 -- badjs-web、badjs-acceptor、badjs-storage、badjs-mq 各自都有自己的端口配置，并且相互之间是有联系的。散落到多个包下，难以理解联系起来，同时也不方便升级

**Comment by caihuiji** [comment]
1. 已经修复完成。
2. 单机可以使用 badjs-installer 安装。  多机才需要理解配置
