### ISSUE TITLE
有没有docker 版本？

### ISSUE THREAD

**Issue by liyatang** [BetterJS/doc#12]
rt，环境问题确实是很折腾。 在mac上折腾后终于成功了。 想切到服务器上，又要折腾，而且环境更复杂。

如果有个docker镜像就方便很多了

**Comment by caihuiji** [comment]
近期弄一下。 
主要是 zmq 安装比较麻烦

**Comment by liyatang** [comment]
我还遇到更坑的，gcc  g++ 你说过要4.9。 然而腾讯云上的版本是4.6。然而腾讯云还不建议用户自行升级版本，说什么有问题后果自负。  
无语了

**Comment by miniflycn** [comment]
@liyatang  可以把gcc装在另一个目录，临时link，编译完再切回旧版

**Comment by caihuiji** [comment]
@liyatang  node 升级5 以后。发现很多包需要 4.9 配合编译，否则编译不过的。

**Comment by caihuiji** [comment]
已经使用 axon 替换了 zmq ， 极简安装了

**Comment by liyatang** [comment]
赞效率

**Comment by liyatang** [comment]
报喜，刚刚在linux机器上成功部署了。 感谢betterjsteam.
