### ISSUE TITLE
什么时候支持sourcemap？

### ISSUE THREAD

**Issue by Mrlilili** [BetterJS/doc#20]
RT

**Comment by loskael** [comment]
已经支持 sourcemap，不过要真正用起来还需要你项目做一些调整：
1. 调整构建（webpack、gulp等）的配置，在 build dist 时生成 soucemap 文件
2. 将生成的 sourcemap 文件同步到服务器（建议在公司内网部署一个静态文件服务器）
3. 修改 gateway 配置，将 sourcemap文件（*.map ）转发到静态文件服务器即可

PS. 可以使用  https://github.com/BetterJS/badjs-sourcemap 和 https://github.com/BetterJS/badjs-sourcemap-server 做文件同步也可以使用 rsync 之类的工具做

另外，可以看一下这个 http://imweb.io/topic/565c49f23ad940357eb9986e

**Comment by Mrlilili** [comment]
这样的话，每次发版本会连同sourcemap文件一起发到生产环境？
不知理解错没

**Comment by miniflycn** [comment]
👍👍

**Comment by Mrlilili** [comment]
为什么要单独弄一台服务器存sourcemap文件，跟项目一起发到线上有什么弊端？

**Comment by miniflycn** [comment]
弊端是源代码给人家看见了啊～如果你们觉得源代码给人看到不是问题，那就不是问题咯

**Comment by Mrlilili** [comment]
我理解的是，开发调试的时候将JS代理到公司内部服务器（有sourcemap的），线上用户环境没有sourcemap，这样理解正确么？

**Comment by loskael** [comment]
是的
