### ISSUE TITLE
docker 部署

### ISSUE THREAD

**Issue by ctocto** [BetterJS/doc#27]
执行 `docker run -i -d -p 80:80 -p 8081:8081 docker.io/caihuijigood/badjs-docker bash badjs mysql=mysql://root:root@localhost:3306/badjs mongodb=mongodb://localhost:27017/badjs` 语句后没有效果
![wechatimg269](https://user-images.githubusercontent.com/16641120/43305911-00e86a20-91ac-11e8-9594-7cb880dbaf92.jpeg)

**Comment by hank-cp** [comment]
localhost指向的是docker实例, 这个docker镜像并没有数据库. 你要用本地网络的IP地址才行. 

https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach

**Comment by caihuiji** [comment]
是的。docker不提供数据库。
