### ISSUE TITLE
历史查询关键字中带中文导致接口返回错误

### ISSUE THREAD

**Issue by floydcash** [BetterJS/doc#9]
在历史查询中输入中文：缺少对象，接口调用返回错误code: "ECONNRESET"，输入英文:null，则请求成功，应该是对中文处理有问题~~

**Comment by caihuiji** [comment]
1. 已经修复中文查询失败的问题。
2. 搜索的时候其实是可以支持正则。  msg=xxx; 就是绝对搜索了

**Comment by caihuiji** [comment]
![image](https://cloud.githubusercontent.com/assets/2292731/12220058/1bbf1a50-b799-11e5-98a5-80d692f34d6c.png)

其实在mongodb中有一个all 字段 ，搜索的使用时候用这个字段做正则匹配的。 
所以你加 **msg**=xxx**;**  就是只匹配到 msg 中的内容了
